# Generated by Django 3.0.5 on 2020-04-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_id', models.IntegerField(verbose_name='Id type of the leaderboard')),
                ('date', models.DateTimeField(verbose_name='Collection date')),
                ('csv_table', models.FileField(upload_to='', verbose_name='CSV file storing the dataset')),
                ('population', models.IntegerField(verbose_name='Total number of players')),
                ('average_elo', models.FloatField(verbose_name='Average elo')),
            ],
        ),
    ]
