# Generated by Django 3.0.5 on 2020-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='plot',
            field=models.TextField(help_text='HTML plot of the dataset', null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='average_elo',
            field=models.FloatField(help_text='Average elo'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='csv_table',
            field=models.FilePathField(help_text='Path to the CSV file storing the dataset'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='date',
            field=models.DateTimeField(help_text='Collection date'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='leaderboard_id',
            field=models.IntegerField(help_text='Id type of the leaderboard'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='population',
            field=models.IntegerField(help_text='Total number of players'),
        ),
    ]
