# Generated by Django 3.0.5 on 2020-04-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_auto_20200423_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='top_player',
            field=models.CharField(help_text='Top ranking player', max_length=100, null=True),
        ),
    ]
