# Generated by Django 3.0.5 on 2020-04-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0003_leaderboard_top_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='game',
            field=models.CharField(default='aoe2de', help_text='AoE2:DE o AoE2:HD', max_length=10),
            preserve_default=False,
        ),
    ]
