# Generated by Django 3.0.5 on 2020-04-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_leaderboard_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='plot',
            field=models.FilePathField(help_text='Path to the HTML plot of the dataset', null=True),
        ),
    ]
